alias artisan="php artisan"
alias tinker="php artisan tinker"

alias c="composer"
alias cu="composer update"
alias cr="composer require"
alias ci="composer install"
alias cid="composer install --dev"

alias l="ls -laF"

alias y="yarn"
alias yw="yarn watch"
alias yd="yarn dev"
alias ya="yarn add"
alias yad="yarn add -D"
alias yga="yarn global add"
alias yh="yarn hot"
alias yb="yarn build"
alias yp="yarn production"
